// <auto-generated />
namespace WCFService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AirportIDsonRoute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AirportIDsonRoute));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131805278_Airport IDs on Route"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
